package com.portal.emprego.controller;

// Generated by GitHub Copilot

import com.portal.emprego.dto.LoginRequestDTO;
import com.portal.emprego.dto.LoginResponseDTO;
import com.portal.emprego.dto.RegisterRequestDTO;
import com.portal.emprego.model.Usuario;
import com.portal.emprego.security.JwtUtil;
import com.portal.emprego.service.UsuarioService;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

/**
 * Controller responsavel pelas rotas publicas de autenticacao.
 *
 * Rotas:
 *   POST /auth/register -> Cadastra um novo usuario
 *   POST /auth/login    -> Autentica e retorna um token JWT
 */
@RestController
@RequestMapping("/auth")
public class AuthController {

    @Autowired
    private UsuarioService usuarioService;

    /**
     * AuthenticationManager: componente do Spring Security que executa a autenticacao.
     * Internamente chama o DaoAuthenticationProvider (configurado em SecurityConfig)
     * que busca o usuario pelo email e verifica o hash BCrypt da senha.
     */
    @Autowired
    private AuthenticationManager authenticationManager;

    @Autowired
    private JwtUtil jwtUtil;

    /**
     * Cadastra um novo usuario no sistema.
     *
     * Rota publica: qualquer pessoa pode se registrar.
     * A senha e criptografada pelo UsuarioService antes de persistir.
     *
     * POST /auth/register
     * Body: { "nome": "Joao Silva", "email": "joao@email.com", "senha": "senha123" }
     *
     * @param dto dados de cadastro validados pelo Bean Validation
     * @return mensagem de confirmacao com HTTP 201 Created
     */
    @PostMapping("/register")
    public ResponseEntity<String> registrar(@Valid @RequestBody RegisterRequestDTO dto) {
        Usuario usuario = usuarioService.registrar(dto);
        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body("Usuario '" + usuario.getNome() + "' cadastrado com sucesso!");
    }

    /**
     * Autentica o usuario e retorna um token JWT.
     *
     * Fluxo:
     * 1. Recebe email e senha do cliente
     * 2. O AuthenticationManager verifica as credenciais no banco (via BCrypt)
     * 3. Se corretas, gera um token JWT com o email como subject
     * 4. Retorna o token para o cliente
     *
     * POST /auth/login
     * Body: { "email": "joao@email.com", "senha": "senha123" }
     * Response: { "token": "eyJhbGciOiJIUzI1NiIs..." }
     *
     * @param dto credenciais de login validadas
     * @return LoginResponseDTO contendo o token JWT
     */
    @PostMapping("/login")
    public ResponseEntity<LoginResponseDTO> login(@Valid @RequestBody LoginRequestDTO dto) {
        // Delega a autenticacao ao Spring Security
        // Se as credenciais forem invalidas, lanca BadCredentialsException (tratada no GlobalExceptionHandler)
        Authentication auth = authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(dto.getEmail(), dto.getSenha())
        );

        // O principal e o UserDetails retornado pelo loadUserByUsername (nosso Usuario)
        Usuario usuario = (Usuario) auth.getPrincipal();

        // Gera o token JWT assinado para esse usuario
        String token = jwtUtil.gerarToken(usuario);

        return ResponseEntity.ok(new LoginResponseDTO(token));
    }
}
