package com.portal.emprego.controller;

// Generated by GitHub Copilot

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Controller de healthcheck da API.
 *
 * Rota pública: GET /status
 * Útil para monitoramento e para verificar se a API está no ar.
 */
@RestController
public class StatusController {

    /**
     * Verifica se a API está online.
     * GET /status
     *
     * @return mensagem de status HTTP 200 OK
     */
    @GetMapping("/status")
    public ResponseEntity<String> status() {
        return ResponseEntity.ok("API Portal Emprego está online!");
    }
}
