package com.portal.emprego.controller;

// Generated by GitHub Copilot

import com.portal.emprego.model.Usuario;
import com.portal.emprego.service.UsuarioService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * Controller de gerenciamento de usuários.
 *
 * Rota privada: exige token JWT válido no header Authorization.
 * A senha (hash BCrypt) NUNCA é incluída na resposta (@JsonIgnore na entidade).
 */
@RestController
@RequestMapping("/usuarios")
public class UsuarioController {

    @Autowired
    private UsuarioService usuarioService;

    /**
     * Lista todos os usuários cadastrados no sistema.
     *
     * Rota privada: GET /usuarios
     * Header obrigatório: Authorization: Bearer <token>
     *
     * @return lista de usuários (sem o campo senha)
     */
    @GetMapping
    public List<Usuario> listar() {
        return usuarioService.listarTodos();
    }
}
