package com.portal.emprego.service;

// Generated by GitHub Copilot

import com.portal.emprego.dto.RegisterRequestDTO;
import com.portal.emprego.model.Role;
import com.portal.emprego.model.Usuario;
import com.portal.emprego.repository.UsuarioRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Serviço responsável pelas operações de negócio relacionadas aos Usuários.
 */
@Service
public class UsuarioService {

    @Autowired
    private UsuarioRepository usuarioRepository;

    /**
     * BCryptPasswordEncoder injetado do bean definido em SecurityConfig.
     * Usado para transformar a senha em hash antes de salvar.
     */
    @Autowired
    private PasswordEncoder passwordEncoder;

    /**
     * Registra um novo usuário na aplicação.
     *
     * Passos:
     * 1. Verifica se já existe um usuário com o mesmo email (email deve ser único)
     * 2. Criptografa a senha com BCrypt
     * 3. Atribui o papel USER por padrão
     * 4. Salva o usuário no banco de dados
     *
     * @param dto dados do novo usuário (nome, email, senha em texto puro)
     * @return Usuario salvo no banco
     * @throws IllegalArgumentException se o email já estiver cadastrado
     */
    public Usuario registrar(RegisterRequestDTO dto) {
        // Impede cadastros duplicados pelo mesmo email
        if (usuarioRepository.findByEmail(dto.getEmail()).isPresent()) {
            throw new IllegalArgumentException(
                    "Já existe um usuário cadastrado com o email: " + dto.getEmail());
        }

        Usuario usuario = new Usuario();
        usuario.setNome(dto.getNome());
        usuario.setEmail(dto.getEmail());

        // passwordEncoder.encode() gera o hash BCrypt da senha
        // Ex: "senha123" -> "$2a$10$abc..." (nunca reversível)
        usuario.setSenha(passwordEncoder.encode(dto.getSenha()));

        // Todo usuário novo recebe o papel USER (acesso padrão)
        usuario.setRole(Role.USER);

        return usuarioRepository.save(usuario);
    }

    /**
     * Lista todos os usuários cadastrados no sistema.
     * A senha não é exposta na resposta (campo @JsonIgnore na entidade).
     *
     * @return lista de usuários
     */
    public List<Usuario> listarTodos() {
        return usuarioRepository.findAll();
    }
}
