package com.portal.emprego.repository;

// Generated by GitHub Copilot

import com.portal.emprego.model.Usuario;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.Optional;

/**
 * Repositório JPA para a entidade Usuario.
 *
 * findByEmail é usada pelo Spring Security para carregar o usuário durante
 * a autenticação (via UsuarioDetailsService).
 */
public interface UsuarioRepository extends JpaRepository<Usuario, Long> {

    /**
     * Busca um usuário pelo email.
     * Retorna Optional.empty() se não existir nenhum usuário com esse email.
     */
    Optional<Usuario> findByEmail(String email);
}
