package com.portal.emprego.security;

// Generated by GitHub Copilot

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.web.authentication.WebAuthenticationDetailsSource;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;

/**
 * Filtro JWT que intercepta CADA requisição HTTP exatamente uma vez.
 *
 * Fluxo de execução para cada requisição:
 * 1. Lê o header "Authorization" da requisição
 * 2. Verifica se começa com "Bearer " (padrão JWT)
 * 3. Extrai o token e o email de dentro dele
 * 4. Carrega o usuário do banco de dados pelo email
 * 5. Valida o token (assinatura + expiração)
 * 6. Se válido, registra o usuário no contexto de segurança do Spring
 * 7. Passa a requisição para o próximo filtro da cadeia
 *
 * Se não houver token (rota pública), o filtro simplesmente deixa passar
 * e o Spring Security decide se a rota precisa de autenticação.
 */
@Component
public class JwtAuthenticationFilter extends OncePerRequestFilter {

    @Autowired
    private JwtUtil jwtUtil;

    @Autowired
    private UsuarioDetailsService usuarioDetailsService;

    @Override
    protected void doFilterInternal(HttpServletRequest request,
                                    HttpServletResponse response,
                                    FilterChain filterChain)
            throws ServletException, IOException {

        // 1. Lê o cabeçalho Authorization da requisição
        String authHeader = request.getHeader("Authorization");

        // 2. Se não houver cabeçalho ou não começar com "Bearer ", passa para o próximo filtro
        //    (rotas públicas chegam aqui e continuam normalmente)
        if (authHeader == null || !authHeader.startsWith("Bearer ")) {
            filterChain.doFilter(request, response);
            return;
        }

        // 3. Remove o prefixo "Bearer " para obter apenas o token
        String token = authHeader.substring(7);
        String email;

        try {
            // 4. Extrai o email do payload do token (também valida a assinatura)
            email = jwtUtil.extrairEmail(token);
        } catch (Exception e) {
            // Token malformado ou com assinatura inválida -> deixa passar sem autenticar
            // O Spring Security vai negar o acesso a rotas protegidas automaticamente
            filterChain.doFilter(request, response);
            return;
        }

        // 5. Se extraiu o email e o usuário ainda não está autenticado nessa requisição
        if (email != null && SecurityContextHolder.getContext().getAuthentication() == null) {

            // 6. Carrega os dados do usuário do banco de dados
            UserDetails userDetails = usuarioDetailsService.loadUserByUsername(email);

            // 7. Valida o token contra o usuário carregado (email + expiração)
            if (jwtUtil.tokenValido(token, userDetails)) {

                // 8. Cria o objeto de autenticação do Spring Security
                UsernamePasswordAuthenticationToken authToken =
                        new UsernamePasswordAuthenticationToken(
                                userDetails,
                                null,                          // credenciais (null após autenticado)
                                userDetails.getAuthorities()   // permissões do usuário
                        );

                // 9. Adiciona detalhes da requisição HTTP (IP, session) à autenticação
                authToken.setDetails(new WebAuthenticationDetailsSource().buildDetails(request));

                // 10. Registra a autenticação no contexto de segurança para essa requisição
                //     A partir daqui, o Spring sabe que o usuário está autenticado
                SecurityContextHolder.getContext().setAuthentication(authToken);
            }
        }

        // 11. Continua para o próximo filtro na cadeia (e por fim chega ao Controller)
        filterChain.doFilter(request, response);
    }
}
