package com.portal.emprego.security;

// Generated by GitHub Copilot

import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.util.Date;

/**
 * Utilitário responsável por todas as operações com tokens JWT:
 * - Geração do token após login bem-sucedido
 * - Extração do email (subject) de dentro do token
 * - Validação do token (assinatura, expiração, correspondência com o usuário)
 *
 * O token JWT tem três partes separadas por ponto:
 *   HEADER.PAYLOAD.ASSINATURA
 *
 * O PAYLOAD carrega o "subject" (email) e a data de expiração.
 * A ASSINATURA garante que o token não foi alterado.
 */
@Component
public class JwtUtil {

    /**
     * Chave secreta lida do application.properties (jwt.secret).
     * Deve ter pelo menos 32 caracteres para o algoritmo HS256.
     */
    @Value("${jwt.secret}")
    private String secret;

    /**
     * Tempo de validade do token em milissegundos (jwt.expiration).
     * 86400000 ms = 24 horas.
     */
    @Value("${jwt.expiration}")
    private Long expiration;

    /**
     * Converte a string secreta em uma chave criptográfica segura (HMAC-SHA256).
     */
    private SecretKey getSigningKey() {
        return Keys.hmacShaKeyFor(secret.getBytes());
    }

    /**
     * Gera um token JWT para o usuário autenticado.
     *
     * O token contém:
     *   - subject: email do usuário
     *   - issuedAt: momento da geração
     *   - expiration: momento de expiração (agora + jwt.expiration)
     *   - assinatura HMAC-SHA256 com a chave secreta
     *
     * @param userDetails usuário autenticado pelo Spring Security
     * @return token JWT como String
     */
    public String gerarToken(UserDetails userDetails) {
        return Jwts.builder()
                .subject(userDetails.getUsername())           // email como identificador
                .issuedAt(new Date())                         // data/hora de emissão
                .expiration(new Date(System.currentTimeMillis() + expiration)) // expiração
                .signWith(getSigningKey())                    // assina com HMAC-SHA256
                .compact();                                   // compacta para String
    }

    /**
     * Extrai o email (subject) armazenado dentro do token JWT.
     *
     * @param token token JWT recebido no header Authorization
     * @return email do usuário dono do token
     */
    public String extrairEmail(String token) {
        return Jwts.parser()
                .verifyWith(getSigningKey())   // verifica a assinatura
                .build()
                .parseSignedClaims(token)      // faz o parse e valida
                .getPayload()
                .getSubject();                 // extrai o subject (email)
    }

    /**
     * Valida se um token é legítimo para o usuário informado.
     *
     * Verifica:
     * 1. O email do token corresponde ao usuário carregado do banco
     * 2. O token não está expirado
     * 3. A assinatura é válida (se fosse adulterada, extrairEmail lançaria exceção)
     *
     * @param token       token JWT da requisição
     * @param userDetails usuário carregado do banco de dados
     * @return true se o token for válido; false caso contrário
     */
    public boolean tokenValido(String token, UserDetails userDetails) {
        try {
            String emailDoToken = extrairEmail(token);
            return emailDoToken.equals(userDetails.getUsername()) && !tokenExpirado(token);
        } catch (JwtException | IllegalArgumentException e) {
            // Token adulterado, inválido ou com formato incorreto
            return false;
        }
    }

    /**
     * Verifica se a data de expiração do token já passou.
     */
    private boolean tokenExpirado(String token) {
        Date expiracao = Jwts.parser()
                .verifyWith(getSigningKey())
                .build()
                .parseSignedClaims(token)
                .getPayload()
                .getExpiration();
        return expiracao.before(new Date());
    }
}
