package com.portal.emprego.security;

// Generated by GitHub Copilot

import jakarta.servlet.http.HttpServletResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpMethod;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.AuthenticationProvider;
import org.springframework.security.authentication.dao.DaoAuthenticationProvider;
import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;

/**
 * Configuração central de segurança da aplicação.
 *
 * Responsabilidades:
 * - Define quais rotas são públicas e quais são privadas
 * - Configura a API como STATELESS (sem sessões HTTP, usando JWT)
 * - Registra o filtro JWT na cadeia de filtros do Spring Security
 * - Configura o BCrypt como algoritmo de hash de senha
 * - Configura o provedor de autenticação que verifica email + senha no banco
 */
@Configuration
@EnableWebSecurity
public class SecurityConfig {

    @Autowired
    private JwtAuthenticationFilter jwtAuthenticationFilter;

    @Autowired
    private UsuarioDetailsService usuarioDetailsService;

    /**
     * Define as regras de segurança HTTP.
     *
     * Aqui mapeamos quais endpoints precisam de autenticação e quais são livres.
     * Também desabilitamos CSRF (não necessário para APIs REST com JWT)
     * e configuramos a política de sessão como STATELESS.
     */
    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        http
            // Desativa proteção CSRF: desnecessária para APIs REST stateless com JWT
            // (CSRF é para formulários web com sessão de browser)
            .csrf(csrf -> csrf.disable())

            // Não armazena sessão no servidor: cada requisição deve trazer o token JWT
            .sessionManagement(session ->
                    session.sessionCreationPolicy(SessionCreationPolicy.STATELESS))

            // Configura a resposta quando o acesso é negado (401 Unauthorized) em JSON
            .exceptionHandling(ex -> ex
                    .authenticationEntryPoint((request, response, authException) -> {
                        response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
                        response.setContentType("application/json;charset=UTF-8");
                        response.getWriter().write(
                                "{\"erro\": \"Acesso negado. Faça login e envie o token JWT no header Authorization: Bearer <token>\"}"
                        );
                    })
            )

            // ================================================================
            // Regras de autorização por rota
            // A ordem importa: do mais específico para o mais genérico
            // ================================================================
            .authorizeHttpRequests(auth -> auth

                // === ROTAS PÚBLICAS (não precisam de token) ===

                // Cadastro e login de usuários
                .requestMatchers(HttpMethod.POST, "/auth/register", "/auth/login").permitAll()

                // Rota de status da API
                .requestMatchers(HttpMethod.GET, "/status").permitAll()

                // Listagem e consulta de vagas e cursos (leitura pública)
                .requestMatchers(HttpMethod.GET, "/vagas", "/vagas/**").permitAll()
                .requestMatchers(HttpMethod.GET, "/cursos", "/cursos/**").permitAll()

                // === ROTAS PRIVADAS (precisam de token JWT válido) ===

                // Criação de vagas e cursos: apenas autenticados
                .requestMatchers(HttpMethod.POST, "/vagas", "/cursos").authenticated()

                // Atualização de vagas e cursos: apenas autenticados
                .requestMatchers(HttpMethod.PUT, "/vagas/**", "/cursos/**").authenticated()

                // Remoção de vagas e cursos: apenas autenticados
                .requestMatchers(HttpMethod.DELETE, "/vagas/**", "/cursos/**").authenticated()

                // Listagem de usuários: apenas autenticados
                .requestMatchers(HttpMethod.GET, "/usuarios").authenticated()

                // Qualquer outra rota não mapeada também exige autenticação (segurança por padrão)
                .anyRequest().authenticated()
            )

            // Registra o filtro JWT ANTES do filtro de autenticação padrão do Spring
            // Assim, o JWT é processado em toda requisição antes de qualquer outra checagem
            .addFilterBefore(jwtAuthenticationFilter, UsernamePasswordAuthenticationFilter.class);

        return http.build();
    }

    /**
     * Bean do encoder de senha.
     *
     * BCrypt é o algoritmo recomendado para hash de senhas:
     * - Gera um salt aleatório em cada operação (mesmo input -> outputs diferentes)
     * - É computacionalmente custoso (dificulta ataques de força bruta)
     * - Exemplo: "minhasenha" -> "$2a$10$xyz..."
     */
    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }

    /**
     * Provedor de autenticação que usa o banco de dados.
     *
     * Quando alguém faz login, este provider:
     * 1. Chama usuarioDetailsService.loadUserByUsername(email) para buscar o usuário
     * 2. Usa o BCryptPasswordEncoder para comparar a senha enviada com o hash salvo
     * 3. Se bater, autentica; caso contrário, lança BadCredentialsException
     */
    @Bean
    public AuthenticationProvider authenticationProvider() {
        DaoAuthenticationProvider provider = new DaoAuthenticationProvider(usuarioDetailsService);
        provider.setPasswordEncoder(passwordEncoder());
        return provider;
    }

    /**
     * Expõe o AuthenticationManager como bean para uso no AuthController.
     *
     * O AuthController chama authenticationManager.authenticate() para validar
     * as credenciais de login de forma programática.
     */
    @Bean
    public AuthenticationManager authenticationManager(AuthenticationConfiguration config) throws Exception {
        return config.getAuthenticationManager();
    }
}
