package com.portal.emprego.security;

// Generated by GitHub Copilot

import com.portal.emprego.repository.UsuarioRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

/**
 * Serviço que o Spring Security usa para carregar um usuário do banco de dados
 * durante o processo de autenticação.
 *
 * O método loadUserByUsername é chamado automaticamente pelo Spring em dois momentos:
 *   1. Durante o login: para buscar o usuário e verificar a senha com BCrypt
 *   2. Durante a validação do JWT: chamado pelo JwtAuthenticationFilter para
 *      carregar o usuário correspondente ao email do token
 */
@Service
public class UsuarioDetailsService implements UserDetailsService {

    @Autowired
    private UsuarioRepository usuarioRepository;

    /**
     * Busca o usuário no banco pelo email.
     *
     * @param email o "username" no contexto deste sistema (campo email do Usuario)
     * @return o Usuario encontrado (que implementa UserDetails)
     * @throws UsernameNotFoundException se não existir usuário com esse email
     */
    @Override
    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
        return usuarioRepository.findByEmail(email)
                .orElseThrow(() ->
                        new UsernameNotFoundException("Usuário não encontrado com o email: " + email));
    }
}
