package com.portal.emprego.model;

// Generated by GitHub Copilot

/**
 * Enum que representa os papéis (perfis de acesso) de um usuário no sistema.
 * USER  -> usuário comum, acesso às rotas privadas padrão.
 * ADMIN -> administrador, pode ter permissões extras no futuro.
 */
public enum Role {
    USER,
    ADMIN
}
