package com.portal.emprego.model;

// Generated by GitHub Copilot

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collection;
import java.util.List;

/**
 * Entidade que representa um usuário do sistema.
 *
 * Implementa UserDetails para integração direta com o Spring Security,
 * permitindo que o Spring use essa entidade como fonte de autenticação.
 *
 * A senha NUNCA é armazenada em texto puro — sempre como hash BCrypt.
 * O campo senha é marcado com @JsonIgnore para nunca aparecer nas respostas da API.
 */
@Entity
@Table(name = "usuarios")
@Getter
@Setter
public class Usuario implements UserDetails {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Nome completo do usuário */
    private String nome;

    /** Email usado como login; deve ser único no sistema */
    @Column(unique = true, nullable = false)
    private String email;

    /**
     * Hash BCrypt da senha.
     * @JsonIgnore impede que o hash seja exposto nas respostas JSON da API.
     */
    @JsonIgnore
    private String senha;

    /** Papel do usuário: USER ou ADMIN */
    @Enumerated(EnumType.STRING)
    private Role role;

    // =========================================================
    // Métodos obrigatórios da interface UserDetails
    // O Spring Security usa esses métodos para autenticar o usuário
    // =========================================================

    /**
     * Retorna as autoridades (permissões) do usuário.
     * Ex: role=USER -> authority="ROLE_USER"
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return List.of(new SimpleGrantedAuthority("ROLE_" + role.name()));
    }

    /**
     * Retorna a senha (hash BCrypt). O Spring Security usa para verificar o login.
     */
    @Override
    public String getPassword() {
        return senha;
    }

    /**
     * O username no Spring Security é o email neste projeto.
     */
    @Override
    public String getUsername() {
        return email;
    }

    /** Conta não expirada */
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    /** Conta não bloqueada */
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    /** Credenciais não expiradas */
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /** Conta ativa */
    @Override
    public boolean isEnabled() {
        return true;
    }
}
