package com.portal.emprego.dto;

// Generated by GitHub Copilot

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * DTO de saída para a rota POST /auth/login.
 *
 * Retornado ao cliente após autenticação bem-sucedida.
 * O cliente deve guardar esse token e enviá-lo no header:
 *   Authorization: Bearer <token>
 */
@Getter
@AllArgsConstructor
public class LoginResponseDTO {

    /**
     * Token JWT assinado com a chave secreta do servidor.
     * Válido por 24 horas (configurável em application.properties).
     */
    private String token;
}
