package com.portal.emprego.dto;

// Generated by GitHub Copilot

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.Setter;

/**
 * DTO de entrada para a rota POST /auth/login.
 *
 * Contém as credenciais que o usuário envia para autenticar-se.
 * As validações garantem que os campos não chegam vazios.
 */
@Getter
@Setter
public class LoginRequestDTO {

    /** Email do usuário (usado como username no sistema) */
    @NotBlank(message = "O email é obrigatório.")
    @Email(message = "Informe um email válido.")
    private String email;

    /** Senha em texto puro (será comparada ao hash BCrypt salvo no banco) */
    @NotBlank(message = "A senha é obrigatória.")
    private String senha;
}
