package com.portal.emprego.dto;

// Generated by GitHub Copilot

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;

/**
 * DTO de entrada para a rota POST /auth/register.
 *
 * Contém os dados necessários para criar uma nova conta de usuário.
 * A senha recebida aqui será criptografada com BCrypt antes de ser salva.
 */
@Getter
@Setter
public class RegisterRequestDTO {

    /** Nome completo do novo usuário */
    @NotBlank(message = "O nome é obrigatório.")
    private String nome;

    /** Email que será usado como credencial de login (deve ser único) */
    @NotBlank(message = "O email é obrigatório.")
    @Email(message = "Informe um email válido.")
    private String email;

    /**
     * Senha em texto puro.
     * Será transformada em hash BCrypt pelo UsuarioService antes de persistir.
     * Mínimo de 6 caracteres para garantir segurança mínima.
     */
    @NotBlank(message = "A senha é obrigatória.")
    @Size(min = 6, message = "A senha deve ter pelo menos 6 caracteres.")
    private String senha;
}
